{% set name = "ceffyl" %}
{% set version = "1.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astrolamb/ceffyl/archive/v{{ version }}.tar.gz
  sha256: 5dc4d555bb214c47a877073ac123a63ad3292beea58435d7bc0d2f7e28972bed

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - numpy >=1.23.5,<2.0.0
    - cython >=0.29.33,<1.0.0
    - pip
  run:
    - python
    - cython >=0.29.37,<1.0.0
    - encor >=1.1.2
    - enterprise-pulsar >=3.4.1,<4.0.0
    - enterprise_extensions >=2.4.2,<3.0.0
    - h5py >=3.11.0,<4.0.0
    - kalepy >=1.4,<2.0.0
    - kdepy >=1.1.0,<2.0.0
    - la_forge >=1.1.0,<2.0.0
    - natsort >=8.4.0,<9.0.0
    - ptmcmcsampler >=2.1.2,<3.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ceffyl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astrolamb/ceffyl/
  dev_url: https://github.com/astrolamb/ceffyl/
  summary: A software package to rapidly and flexibly analyse pulsar timing array data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrolamb
    - davecwright3
